### ISSUE TITLE
Auto Installer not Able to download 

### ISSUE THREAD

**Issue by nemesis128** [tim241/BetterMajorasMaskInstaller#6] opened 2020-06-14 08:11 UTC
Error at first step running the downloader 
![image](https://user-images.githubusercontent.com/8691583/84588390-990eea00-adec-11ea-8af8-b8b1ed4a939c.png)

On Friday the Installer worked fine, but re-installing today didn't work

**Comment by tim241** [comment] 2020-06-14 08:14
Thank you, will take a look at that today.

**Comment by tim241** [comment] 2020-06-14 10:53
I can't reproduce that issue sadly
![image](https://user-images.githubusercontent.com/18737914/84591366-fe3efb80-ae3d-11ea-9440-fdb0bc8a99be.png)

**Comment by tim241** [comment] 2020-06-14 11:12
I've pushed a fix (hopefully) https://github.com/tim241/BetterMajorasMaskInstaller/commit/7cda8c2e0d2d4a123277986abdffa1b0c3d30479
and released a new version with that fix
https://github.com/tim241/BetterMajorasMaskInstaller/releases/tag/3.2.2

if it happens again, feel free to re-open the issue!

**Closed by tim241** 2020-06-14 11:12 UTC
